version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 /workspace/server.py --test_data_path /workspace/test.csv --num_rounds 30 --address server:5040
    volumes:
      - .:/workspace

  client1:
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 /workspace/client.py --client_data_path /workspace/client1.csv --label_column prevalentHyp --address server:5040
    volumes:
      - .:/workspace
    depends_on:
      - server

  client2:
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 /workspace/client.py --client_data_path /workspace/client2.csv --label_column TenYearCHD --address server:5040
    volumes:
      - .:/workspace
    depends_on:
      - server